name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Installation des dépendances
        run: |
          npm install
          
      - name: Construction de l'image Docker
        run: |
          docker build -t siyourself/csa-frontend:tagname .

      - name: Connexion à Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push vers Docker Hub
        run: |
          docker push siyourself/csa-frontend:tagname
